# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='n_horas',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
