# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_asistenciaestudiante_n_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='n_horas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
