# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_auto_20170418_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='foto_url',
            field=models.URLField(null=True),
        ),
    ]
