# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0008_auto_20170328_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='fecha_asistencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
