# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0010_auto_20170328_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaestudiante',
            options={'verbose_name': 'Asistencia', 'verbose_name_plural': 'Lista de asistencia'},
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='asistio',
            field=models.NullBooleanField(default=False),
        ),
    ]
