# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_actividad_tipo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
