# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20170328_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Registro Actividad',
            },
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='Cupo_Actividad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='TipoActividad',
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividad'),
        ),
        migrations.AddField(
            model_name='registroactividad',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Servicio'),
        ),
    ]
