# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('semestre', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('facultad', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipodeParticipacion', models.CharField(choices=[('Curso', 'Curso'), ('Grupo de representacion', 'Grupo de representacion'), ('Equipos de representacion', 'Equipos de representacion'), ('Brigada', 'Brigada'), ('Otro', 'Otro')], max_length=30)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Estudiantes')),
            ],
        ),
    ]
