# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asistencia', models.DateField(default=django.utils.timezone.now)),
                ('asistio', models.NullBooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Historia Asistencia',
                'verbose_name_plural': 'Hisorial de asistencia',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('ID_Estudiante', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Primer_Nombre', models.CharField(max_length=30, null=True)),
                ('Segundo_Nombre', models.CharField(max_length=30, null=True)),
                ('Primer_Apellido', models.CharField(max_length=30, null=True)),
                ('Segundo_Apellido', models.CharField(max_length=30, null=True)),
                ('Nro_Documento', models.CharField(max_length=30)),
                ('Tipo_Documento', models.CharField(choices=[('TI', 'TI'), ('CC', 'CC')], max_length=30)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=30, null=True)),
                ('Correo_Institucional', models.EmailField(max_length=50, unique=True)),
                ('Nro_Telefonico', models.CharField(max_length=30, null=True)),
                ('Ciclo_Lectivo', models.CharField(max_length=30, null=True)),
                ('Descripcion', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now=True, null=True)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Estudiantes')),
                ('programacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programacion.Programacion')),
            ],
            options={
                'verbose_name': 'Inscripcion individual',
                'verbose_name_plural': 'Estudiantes Inscritos',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='Programa_Academico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Programa'),
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Estudiantes'),
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='programacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Programacion'),
        ),
    ]
