# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='Instructor',
        ),
    ]
