# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_remove_programacion_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaactividad',
            options={'verbose_name_plural': 'Dias Actividades'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name_plural': 'Horas'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='programacion',
            options={'verbose_name': 'Actividad pogramada', 'verbose_name_plural': 'Actividades Programadas'},
        ),
    ]
