# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
        ('actividades', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora_inicio', models.TimeField(blank=True, null=True)),
                ('Hora_Final', models.TimeField(blank=True, null=True)),
                ('Fecha_Inicio', models.DateField(blank=True, null=True)),
                ('Fecha_Final', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreLugar', models.CharField(choices=[(b'Canchas Deportivas', b'Canchas Deportiva'), (b'Teatrino', b'Teatrino'), (b'Cafeteria', b'Cafeteria'), (b'Auditorio', b'Auditorio'), (b'7mo Piso', b'7mo Piso'), (b'Otro', b'Otro')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Servicio')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividad')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Horario')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Inscripcion')),
                ('lugarActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.Lugar')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor')),
            ],
        ),
    ]
