# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
        ('inscripcion', '0002_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='Instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.Instructor'),
        ),
    ]
