# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_ucc', models.IntegerField(primary_key=True, serialize=False)),
                ('Identificacion', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=30)),
                ('Primer_Apellido', models.CharField(max_length=20)),
                ('Segundo_Apellido', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[(b'ACTIVO', b'Activo'), (b'INACTIVO', b'Inactivo')], default=b'ACTIVO', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
            },
        ),
    ]
