# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_auto_20170307_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
    ]
